### ISSUE TITLE
Irrelevant exception message on fonts

### ISSUE THREAD

**Issue by ambroisemaupate** [psliwa/PHPPdf#105]
I’ve got an error however the font file is here!
> Font "/var/www/files/fonts/a1bdc0c2/chaletbookbold.ttf" not found.

So I looked for the thrown exception.

In /vendor/psliwa/php-pdf/lib/PHPPdf/Core/Engine/ZF/Font.php, `getResourceByStyle`

```php
catch(\ZendPdf\Exception\ExceptionInterface $e)
{
    throw InvalidResourceException::invalidFontException($this->fontResources[$style], $e);
}
```

Then I removed this try-catch and TADA

> This font cannot be embedded in the PDF document. If you would like to use it anyway, you must pass \ZendPdf\Font::EMBED_SUPPRESS_EMBED_EXCEPTION in the $options parameter of the font constructor.

The **real** error is not that font file does not exist but that the TTF file is restricted. So I suggest that you should not catch Zend/Exception that way, because you can look for a long time when your error message is irrelevant.

You should change 

```php
public static function invalidFontException($fontData, \Exception $previous = null)
{
    return new self(sprintf('Font "%s" not found.', $fontData), 0, $previous);
}
```

to:

```php
public static function invalidFontException($fontData, \Exception $previous = null)
{
    return new self(sprintf('Font "%s": '.$previous->getMessage(), $fontData), 0, $previous);
}
```

Because Zend will tell you if the font file is really not found.

**Comment by psliwa** [comment]
Thanks for investigation. I will take care of this asap.

**Comment by ambroisemaupate** [comment]
I can PR this for you if you prefer. 🙂
