### ISSUE TITLE
Node init fails (almost) random

### ISSUE THREAD

**Issue by Thorry84** [psliwa/PHPPdf#114]
Call to a member function saveGS() on null in /vendor/psliwa/php-pdf/lib/PHPPdf/Core/ComplexAttribute/ComplexAttribute.php on line 81 .

This occurs because the preFormat isn't called on a node where it should be. The reason for this is within the Node manager the key in the preFormatInvoked array is the spl_object_hash, but these aren't unique. PHP reuses object hashes, causing the library to fail at seemingly random moments, once PHP reuses a hash for a node previously used for an initialized node, the node doesn't get initialized and fails.

**Comment by Thorry84** [comment]
I've added a pull request to fix this problem: https://github.com/psliwa/PHPPdf/pull/113

**Comment by psliwa** [comment]
Thanks! I will review this PR asap.

**Comment by psliwa** [comment]
PR has been merged.
