### ISSUE TITLE
fopen font issue

### ISSUE THREAD

**Issue by mikevolmar** [psliwa/PHPPdf#117]
Our web server started throwing these errors when generating a pdf with php-pdf. It worked fine with no errors until yesterday.  The path "fopen(/tmp/cachedTimes-Roman.php)" looks wrong to me, it isn't the path to the font file in php-pdf tree, perhaps it is a tmp/ copy of the font?  The pdf still generates fine.  Error still happens when I comment out the font selection statement.  Unsure why this issue started or how to fix it.  Also concerned that it just started seemingly on its own.  

Warning: fopen(/tmp/cachedTimes-Roman.php) [function.fopen]: failed to open stream: Permission denied in /home/site/public_html/include/pdf-php/src/Cpdf.php on line 2039

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/site/public_html/include/pdf-php/src/Cpdf.php on line 2040

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/site/public_html/include/pdf-php/src/Cpdf.php on line 2041

**Comment by psliwa** [comment]
There is no `Cpdf.php` file in `PHPPdf` library. Maybe you use different pdf library.
