### ISSUE TITLE
repeat table header on dynamic pages

### ISSUE THREAD

**Issue by doppynl** [psliwa/PHPPdf#36]
Hi,

I'm creating a long table on a dynamic page. This sometimes results in rows being pushed to the next page. This works fine.

Is there a way to repeat the first row, which I use as a table header, on any subsequent pages?

Thanks,
DoppyNL

**Comment by franciscomemoli** [comment]
This feature is going to be implemented? Do you have any alternative solution to do it?

**Comment by duartesantos** [comment]
I also need this feature.

If you guys have an alternative solution please share it.
