### ISSUE TITLE
Auto heigth with fixed width

### ISSUE THREAD

**Issue by codekorz** [psliwa/PHPPdf#88]
Hey, i want to set a auto heigth of my pdf generate. Heigth based on content of pdf, and witdth set to 80mm i tried with page-size="80mm:auto" but it didnt work.

Maybe its a stupid question, but i was searching in the docs and i dont find how to do it. Im using the plugin in symfony2 with your bundle.

Thanks a lot!

**Comment by psliwa** [comment]
Maybe `elastic-page` tag would help you? https://github.com/psliwa/PHPPdf#standard-tags

**Comment by codekorz** [comment]
Yes, thank you and sorry. I look in doc and i did not see it :$ 

Thank you!
